name: Code Audit

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    name: Code audit

    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4

      - name: â“ Check if .editorconfig exists
        uses: andstor/file-existence-action@v3
        with:
          files: ".editorconfig"
          fail: true

      - name: ğŸ™ˆ Ensure node_modules is ignored by Git
        uses: dkershner6/gitignore-parser@v2
        with:
          must_deny: "node_modules"

      - name: ğŸ’¾ Install modules
        run: npm ci

      - name: ğŸ” ESLint validation
        run: npx eslint src --max-warnings 0
