name: Testing

on: push

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL}}

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4

      - name: ðŸ’¾ Install modules
        run: npm ci

      - name: ðŸ§ª Testing
        run: npm test
